### ISSUE TITLE
如何使用呢？

### ISSUE THREAD

**Issue by haofrank** [wenzouquan/phpkit-aliyun-logger#1]
请问我在 ues 的时候命名空间怎么写呢？

**Comment by wenzouquan** [comment]
1 . 安装依赖  composer require phpkit/aliyun-logger

2. 实例化  
$logger = new \phpkit\aliyunLogger();  //  use \phpkit\aliyunLogger as $logger
$logger->log($array);

**Comment by wenzouquan** [comment]
1 . 安装依赖 composer require phpkit/aliyun-logger

2.实例化
use \phpkit\aliyunLogger as logger;
$logger = new logger($params); // 
$logger->log($array);

**Comment by haofrank** [comment]
ths
